apiVersion: v1
metadata:
  name: "$OPENSHIFT_CLUSTER"
baseDomain: "$OPENSHIFT_DOMAIN"
compute:
  - name: worker
    replicas: 0
controlPlane:
  name: master
  replicas: 1
  architecture: arm64
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  machineNetwork:
    - cidr: "$CIDR"
  networkType: OVNKubernetes
  serviceNetwork:
    - 172.30.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/vda
fips: false
pullSecret: $PULL_SECRET
sshKey: "$SSH_KEY_LOCAL"