apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-ca-chains
data:
  registry.access.redhat.com: |
    -----BEGIN CERTIFICATE-----
    MIIGXjCCBUagAwIBAgIQC0uWkwW/OFXx+ufSt9RS8DANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMSkwJwYDVQQDEyBE
    aWdpQ2VydCBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTAeFw0yMzExMjkwMDAwMDBa
    Fw0yNDEyMDMyMzU5NTlaMHAxCzAJBgNVBAYTAlVTMRcwFQYDVQQIEw5Ob3J0aCBD
    YXJvbGluYTEQMA4GA1UEBxMHUmFsZWlnaDEWMBQGA1UEChMNUmVkIEhhdCwgSW5j
    LjEeMBwGA1UEAxMVY2RuLXB1YmxpYy5yZWRoYXQuY29tMFkwEwYHKoZIzj0CAQYI
    KoZIzj0DAQcDQgAEQ42lZ4YkYqwZJT28v/xjsyTx6TEkJiL3VeSvIYQJYZAOYlLK
    8HiXAeOMBqa4qRaUV0kh2+nqHTUUKVxXX0yzuqOCA94wggPaMB8GA1UdIwQYMBaA
    FLdrouqoqoSMeeq02g+YssWVdrn0MB0GA1UdDgQWBBQzDY4Jogp5icbAxzkhpJ92
    HUm+fjCBhAYDVR0RBH0we4IVY2RuLXB1YmxpYy5yZWRoYXQuY29tghVhY2Nlc3Mu
    Y2RuLnJlZGhhdC5jb22CEmNkbi11YmkucmVkaGF0LmNvbYIacmVnaXN0cnkuYWNj
    ZXNzLnJlZGhhdC5jb22CG3JlZ2lzdHJ5LmNvbm5lY3QucmVkaGF0LmNvbTA+BgNV
    HSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRpZ2lj
    ZXJ0LmNvbS9DUFMwDgYDVR0PAQH/BAQDAgOIMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjCBjwYDVR0fBIGHMIGEMECgPqA8hjpodHRwOi8vY3JsMy5kaWdp
    Y2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLTQuY3JsMECgPqA8
    hjpodHRwOi8vY3JsNC5kaWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYy
    MDIwQ0ExLTQuY3JsMH8GCCsGAQUFBwEBBHMwcTAkBggrBgEFBQcwAYYYaHR0cDov
    L29jc3AuZGlnaWNlcnQuY29tMEkGCCsGAQUFBzAChj1odHRwOi8vY2FjZXJ0cy5k
    aWdpY2VydC5jb20vRGlnaUNlcnRUTFNSU0FTSEEyNTYyMDIwQ0ExLTEuY3J0MAwG
    A1UdEwEB/wQCMAAwggF/BgorBgEEAdZ5AgQCBIIBbwSCAWsBaQB2AO7N0GTV2xrO
    xVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABjB0pojIAAAQDAEcwRQIgOLXpgANm
    WBeGz5V2ZTB6T+mibZoF8vTQ7cFNvPoe5vMCIQDMeKGNpwmZ/T2UPB8UYONPi/0v
    8Lmxe/1wyh4kah5vdwB3AEiw42vapkc0D+VqAvqdMOscUgHLVt0sgdm7v6s52IRz
    AAABjB0pomoAAAQDAEgwRgIhAMjklIZnO2YYUDhYkPXCbZTEhrvb+wbPjyGD1u5u
    TUVuAiEAg3pl7XmCo4xPixlrjs73pUdieY1i/7iDU+rPc+japioAdgDatr9rP7W2
    Ip+bwrtca+hwkXFsu1GEhTS9pD0wSNf7qwAAAYwdKaJMAAAEAwBHMEUCIQC+K3V0
    h0mFnjnsat1ZTVVPmdFYSrab+nLxol5E5QQ6gwIgUHYXNGEh9HZxsVdNoOWR2aoG
    GFzRfYgxIdQGMG8X+IIwDQYJKoZIhvcNAQELBQADggEBADQ3SfVJIyxOaExCGjEL
    q5uiU/p8Obd8GSWaD+6GOHH28cVFg7DLjRolh9XzQfGW/Oidcn0py6QBYwaKE9Xy
    R7Qh4UTBaBpXLCJw1Kc8JTLFJ0NZ7JwJxy/qLF6pPhE0mBhHD6p35qetmGeF9RcK
    y5g9EHFgH69rykHUZh9WfQR/4+sNoptnmCy4PcAhuzoOGmDYMeJb1jceW48bAlgA
    sWTDuUUBcAplsmEyiIFYtLoSPNwRhvh6mwZeQiEJ63b1g8biiTrnNlziTXNXsp8T
    BJV+O7zAAJT/Eyk+rOf8SXF2/5qT6wk4V77DuUGPKXHmR2Gaw9MG/m79S+htbpDg
    2Xg=
    -----END CERTIFICATE-----
